apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text4shell-patched-v1
  name: text4shell-patched-v1
  namespace: text4shell-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: text4shell-patched-v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: text4shell-patched-v1
    spec:
      containers:
      - image: ghcr.io/aaronm-sysdig/text4shell-docker-patched:29
        imagePullPolicy: Always
        name: text4shell-docker-patched-v1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text4shell-patched-v2
  name: text4shell-patched-v2
  namespace: text4shell-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: text4shell-patched-v2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: text4shell-patched-v2
    spec:
      containers:
      - image: ghcr.io/aaronm-sysdig/text4shell-docker-patched:25
        imagePullPolicy: Always
        name: text4shell-docker-patched-v2
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: text4shell-vuln
  name: text4shell-vuln
  namespace: text4shell-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: text4shell-vuln
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: text4shell-vuln
    spec:
      containers:
      - image: ghcr.io/aaronm-sysdig/text4shell-docker-vuln:latest
        imagePullPolicy: Always
        name: text4shell-docker-vuln
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

